workspace = { members = ["p7_1_string_slice"] }
[package]
name = "p7_ownership"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
